		word: ["Abre"],
		word: ["Abu"],
		word: ["Adiós"],
		word: ["Agua"],
		word: ["Allí"],
		word: ["Alta"],
		word: ["Álvaro"],
		word: ["Ana"],
		word: ["Ascensor"],
		word: ["Autobús"],
		word: ["Avión"],
		word: ["Ballena"],
		word: ["Balón"],
		word: ["Bebé"],
		word: ["Beee", "Oveja"],
		word: ["Bien"],
		word: ["Camión"],
		word: ["Cereales"],
		word: ["Ciao"],
		word: ["Coche"],
		word: ["Cocodrilo"],
		word: ["Cua-cua", "Pato"],
		word: ["Dientes"],
		word: ["Dormir"],
		word: ["Eli"],
		word: ["Estrella"],
		word: ["Félix"],
		word: ["Gracias"],
		word: ["Guapa"],
		word: ["Guau-guau", "Perro"],
		word: ["Hala"],
		word: ["Hasta luego"],
		word: ["Héctor"],
		word: ["Hola"],
		word: ["Inés"],
		word: ["Irene"],
		word: ["Isabel"],
		word: ["Kikiriki", "Gallo"],
		word: ["Lápiz"],
		word: ["Luz"],
		word: ["Magdalenas"],
		word: ["Mamá"],
		word: ["Mara"],
		word: ["Miau", "Gato"],
		word: ["Moto"],
		word: ["Mucho"],
		word: ["Muuuu", "Vaca"],
		word: ["Muy bien"],
		word: ["Nariz"],
		word: ["No"],
		word: ["Oink", "Cerdo"],
		word: ["Oso"],
		word: ["Oye"],
		word: ["Pajaroto"],
		word: ["Papá"],
		word: ["Pato"],
		word: ["Petit"],
		word: ["Pez"],
		word: ["Pie"],
		word: ["Pipí"],
		word: ["Pocoyó"],
		word: ["Pulpo"],
		word: ["Rana"],
		word: ["Si"],
		word: ["Taxi"],
		word: ["Tesoro"],
		word: ["Teta"],
		word: ["Tía"],
		word: ["Tractor"],
		word: ["Vamos"],
		word: ["Vaya cagada"],
		word: ["Yoghurt"],
		word: ["Zapatos"],
